### ISSUE TITLE
Update to 3.3.0

### ISSUE THREAD

**Issue by 2m** [adriansahlman/mypy-protobuf-bufbuild#1]
mypy-protobuf 3.3.0 was released recently: https://github.com/nipunn1313/mypy-protobuf/releases/tag/v3.3.0

**Comment by adriansahlman** [comment]
Hey, I'll make sure to update it today

**Comment by adriansahlman** [comment]
I have pushed the updated plugin to buf, give me a shout if you have any issues with it
